import os
import re
import yaml
import logging
from datetime import datetime
from operator import setitem

from .application import ApplicationNotebook

logger = logging.getLogger(__name__)

LOCAL_PATH = os.path.dirname(os.path.realpath(__file__))

def write_cwl_file(fname, target):
    """Writes [target] dictionary to a .cwl file with filename [fname]."""

    with open(fname, 'w', encoding='utf-8') as f:
        f.write("#!/usr/bin/env cwl-runner\n")
        yaml.dump(target, f, default_flow_style=False)

class CWLError(Exception):
    pass

class BaseCWL(object):

    def __init__(self, application : ApplicationNotebook, template_dir=os.path.join(LOCAL_PATH, 'templates')):

        self.app = application
        self.template_dir = template_dir

    def _read_template(self, app_cwl_fname):
        """Loads the template application CWL."""
        with open(app_cwl_fname, 'r') as f:
            return yaml.safe_load(f)

    def generate_all(self, outdir, **kwargs):
        """Calls all of the application CWL generators as well as the application descriptor generator.

        Returns the list of all files generated by this function (abs. path).
        """

        raise NotImplementedError("Only subclasses of this class implement this method")

class ProcessCWL(BaseCWL):

    def __init__(self, application, repo_info, **kwargs):

        super().__init__(application, **kwargs)
        
        # Used to build metadata
        self.repo_info = repo_info

        # Template CWL and descriptor files
        self.process_cwl = self._read_template( os.path.join(self.template_dir, 'process.cwl'))

    @property
    def _workflow(self):

        graph = self.process_cwl['$graph']
        search_func = lambda d: "class" in d and d["class"] == "Workflow"
        return next(filter(search_func, graph), None)

    @property
    def _command_line_tool(self):

        graph = self.process_cwl['$graph']
        search_func = lambda d: "class" in d and d["class"] == "CommandLineTool"
        return next(filter(search_func, graph), None)

    def generate_all(self, outdir, dockerurl="undefined", **kwargs):
        """Calls all of the application CWL generators as well as the application descriptor generator.

        Returns the list of all files generated by this function (abs. path).
        """

        generated_files = []
        generated_files.append(self.generate_process_cwl(outdir, dockerurl))

        return generated_files

    def _insert_argument_params(self):
        "Connect non stage in/out arguments to papermill parameters"

        # Forward the ordinary argument parameters to the process step directly
        workflow_input_dict = self._workflow['inputs']
        workflow_process_in_dict = self._workflow['steps']['process']['in']
        cmd_input_dict = self._command_line_tool['inputs']

        for param in self.app.arguments:
            param_name = param.name

            param_def = {
                'type': param.cwl_type,
                'default': param.default,
                'label': "argument",
                'doc': param.help,
            }

            cmd_input_dict[param_name] = param_def.copy()
            workflow_input_dict[param_name] = param_def.copy()

            workflow_process_in_dict[param_name] = param_name

    def _insert_input_params(self):
        "Connects the special 'input' CWL parameter to the papermill parameter for receiving the stage-in directory location"

        workflow_input_dict = self._workflow['inputs']
        workflow_process_in_dict = self._workflow['steps']['process']['in']
        cmd_input_dict = self._command_line_tool['inputs']
        
        # The input Directory is carried as an input from stage_in to process to
        # make sure that the contents are exposed to the process container
        #
        # If we had the stage_in collection filename be an input argument
        # to process.cwl then it would be volume mounted in a separate path
        # and we could not assume that the collection file is in the same
        # directory as the staged in results
        if self.app.stage_in_param is not None:
            param_name = self.app.stage_in_param.name

            param_def = {
                'type': "Directory",
                'label': "stage-in",
                'doc': self.app.stage_in_param.help,
            }

            cmd_input_dict[param_name] = param_def.copy()
            workflow_input_dict[param_name] = param_def.copy()

            self._command_line_tool['arguments'] = self._command_line_tool.get('arguments', [])
            self._command_line_tool['arguments'] += [
                '-p', self.app.stage_in_param.name,
                f'$(inputs.{param_name}.path)'
            ]

            workflow_process_in_dict[param_name] = param_name

    def _insert_output_params(self):
        "Connects the special 'input' CWL parameter to the papermill parameter for receiving the stage-out directory location"

        if self.app.stage_out_param is not None:
            stage_out_process_dir = self._command_line_tool['outputs']['outputs_result']['outputBinding']['glob']

            self._command_line_tool['arguments'] = self._command_line_tool.get('arguments', [])
            self._command_line_tool['arguments'] += [
                '-p', self.app.stage_out_param.name, 
                stage_out_process_dir
            ]

        else:
            del self._command_line_tool['outputs']['output']

    def _insert_metadata(self):

        # Defines overridable metadata values for the CWL with a setter function and default value
        # metadata_name: (setter_function, default_value)
        default_metadata = {
            'id': (
                lambda v: setitem(self._workflow, 'id', v), 
                self.repo_info.name
            ),
            'doc': (
                lambda v: setitem(self._workflow, 'doc', v), 
                f"OGC Application for {self.repo_info.name} built from Jupyter notebook: {os.path.basename(self.app.filename)} from source repository: {self.repo_info.source_location}"
            ),
            'label': (
                lambda v: setitem(self._workflow, 'label', v), 
                f"OGC Application for {self.repo_info.name}"
            ),
            'author': (
                lambda v: setitem(self.process_cwl["s:author"][0], "s:name", v), 
                self.repo_info.owner
            ),
            'citation': (
                lambda v: setitem(self.process_cwl, "s:citation", v), 
                self.repo_info.source_location
            ),
            'codeRepository': (
                lambda v: setitem(self.process_cwl, "s:codeRepository", v), 
                self.repo_info.source_location
            ),
            'commitHash': (
                lambda v: setitem(self.process_cwl, "s:commitHash", v), 
                self.repo_info.commit_identifier
            ),
            'dateCreated': (
                lambda v: setitem(self.process_cwl, "s:dateCreated", v), 
                datetime.now().date()
            ),
            'version': (
                lambda v: setitem(self.process_cwl, "s:version", v), 
                "0.1.0"
            ),
            'softwareVersion': (
                lambda v: setitem(self.process_cwl, "s:softwareVersion", v), 
                "0.1.0"
            ),
        }

        # Process all metadata values with a default value
        for keyword, (setter, default_value) in default_metadata.items():
            if keyword in self.app.metadata:
                setter(self.app.metadata[keyword])
            else:
                setter(default_value)

        # Process additional metadata that is not in the list of default values
        for keyword in self.app.metadata:
            if keyword not in default_metadata:
                self.process_cwl[f"s:{keyword}"] = self.app.metadata[keyword]

    def generate_process_cwl(self, outdir, dockerurl):
        """Generates the application CWL.

        Returns the absolute path of the file generated by this function.
        """
        if not os.path.isdir(outdir):
            os.makedirs(outdir)

        # Set correct URL for process Docker container
        self._command_line_tool['requirements']['DockerRequirement']['dockerPull'] = dockerurl

        # Forward the ordinary argument parameters to the process step directly
        self._insert_argument_params()
        
        # Handle input and output parameters and their connection to papermill arguments
        self._insert_input_params()
        self._insert_output_params()

        # Add metadata on the source repository
        self._insert_metadata()

        fname = os.path.join(outdir, 'process.cwl')
        write_cwl_file(fname, self.process_cwl)
        return fname


class DataStagingCWL(BaseCWL):

    def __init__(self, application, **kwargs):
        
        super().__init__(application, **kwargs)

        # Template CWL and descriptor files
        self.workflow_cwl = self._read_template( os.path.join(self.template_dir, 'workflow.cwl'))
        self.stage_in_cwl = self._read_template( os.path.join(self.template_dir, 'stage_in.cwl'))
        self.stage_out_cwl = self._read_template( os.path.join(self.template_dir, 'stage_out.cwl'))

    def generate_all(self, outdir, **kwargs):
        """Calls all of the application CWL generators as well as the application descriptor generator.

        Returns the list of all files generated by this function (abs. path).
        """

        generated_files = []

        generated_files.append(self.generate_workflow_cwl(outdir))
        generated_files.append(self.generate_stage_in_cwl(outdir))
        generated_files.append(self.generate_stage_out_cwl(outdir))

        return generated_files
    
    def generate_workflow_cwl(self, outdir):
        """Generates the workflow CWL.

        Returns the absolute path of the file generated by this function.
        """

        # Preocess step section of of workflow
        process_dict = self.workflow_cwl['steps']['process']

        # Add non stage-in/stage-out inputs to the master CWL input/outputs as parameters
        args_input_dict = self.workflow_cwl['inputs']['parameters']['type']['fields']
        for param in self.app.arguments:
            name = param.name

            # Add argument parameter to workflow input, allow null values so that default parameters 
            # from the notebook can be used
            args_input_dict[name] = [ 'null', param.cwl_type ]

            # Connect process step to input argument with the default coming from the notebook's value
            process_dict['in'][name] = {
                'source': 'parameters',
                'valueFrom': f'$(self.{name})',
            }

        # Connect the stage-in parameter to stage_in's collection filename output
        # Otherwise remove stage in from the workflow
        if self.app.stage_in_param is not None:
            process_dict['in']['input'] = 'stage_in/stage_in_download_dir'
        else:
            # No stage-in connected to notebook, delete
            del self.workflow_cwl['steps']['stage_in']
            del self.workflow_cwl['inputs']['stage_in']

        # Remove stage-out if not defined in the notebook
        # The connection of the parameter given to the notebook is done inside the process.cwl
        if self.app.stage_out_param is None:
            del self.workflow_cwl['steps']['stage_out']
            del self.workflow_cwl['inputs']['stage_out']
            del self.workflow_cwl['outputs']['stage_out_results']

        fname = os.path.join(outdir, 'workflow.cwl')
        write_cwl_file(fname, self.workflow_cwl)
        return fname
 
    def generate_stage_in_cwl(self, outdir):
        """Generates the stage-in CWL.

        Returns the absolute path of the file generated by this function.
        """
        if not os.path.isdir(outdir):
            os.makedirs(outdir)

        # Generate the stage-in CWL as is, no need for modification
        fname = os.path.join(outdir, 'stage_in.cwl')
        write_cwl_file(fname, self.stage_in_cwl)
        return fname
    
    def generate_stage_out_cwl(self, outdir):
        """Generates the stage-in CWL.

        Returns the absolute path of the file generated by this function.
        """
        if not os.path.isdir(outdir):
            os.makedirs(outdir)

        # Generate the outputs CWL as-is, no need for modifications
        fname = os.path.join(outdir, 'stage_out.cwl')
        write_cwl_file(fname, self.stage_out_cwl)
        return fname